class EnvOutput(faust.Record, serializer='json'):
    Id: str = None
    market_prices: str = None
    prev_market_prices: str = None
    tnorm: str = None
    current_pv: str = None
    action: str = None
    prices: str = None
    return_per_annum: float = None
    return_per_month: float = None
    return_per_day: float = None
    return_per_hour: float = None
    return_per_minute: float = None
    sharpe_ratio: float = None
    calmar_ratio: float = None
    burke_ratio: float = None
    omega_ratio: float = None
    kappa_three_ratio: float = None
    sortino_ratio:float = None
    treynor_ratio: float = None
    information_ratio: float = None
    modigliani_ratio: float = None
    max_drawdown: float = None
    average_drawdown: float = None
    total_commission: float = None
    slippage: float = None
    commission_free_return: float = None
    perfect_strategy_return: float = None
    step_rate:float= None
    window_size: float = None
    market: float = None
    volatility: float = None
    beta: float = None
    lower_partial_moment: float = None
    higher_partial_moment: float = None
    var: float=None